Catkin-ProjectName: object_recognition_tod
Version: 0.2.3
Description: Textured Object Recognition a standard bag of features approach

Author: Vincent Rabaud <vrabaud@willowgarage.com>, Ethan Rublee <erublee@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: catkin, ecto, object_recognition_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

